config/routes.rb
Rails.application.routes.draw do
  root  'welcome#index'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :user_weights
  resources :friendships

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image, dependent: :destroy
  has_many :user_weights, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, dependent: :destroy
  has_secure_password

  before_save :downcase_email, :capitalize_first_name, :capitalize_last_name


	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :first_name, presence: true, length: {minimum: 3, maximum: 25}
	validates :last_name, presence: true, length: {minimum: 2, maximum: 25}
	validates :email, presence: true, length: {maximum: 105},
										uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
	validates :password, presence: true, length: {minimum: 6, maximum: 10}

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
           BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attributes(:remember_digest, User.digest(remember_token))
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def capitalize_first_name
  	self.first_name = first_name.capitalize
  end

  def capitalize_last_name
  	self.last_name = last_name.capitalize
  end

end

app/models/user_weight.rb
class UserWeight < ApplicationRecord
  belongs_to :user

  validates :weight, presence: true, numericality: { greater_than: 0, less_than: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    friend = User.find(params[:friend])
    user_friend = current_user.friendships.build(friend_id: friend.id)
    if user_friend.save
      flash.now[:notice] = "#{friend.full_name} add to friend's list"
      redirect_to friendship_path(current_user)
    else
      flash.now[:danger] = "Something went wrong"
      redirect_to users_path
    end
  end

  def show
    @tracked_friends  = current_user.friends.order(:created_at).paginate(page: params[:page], per_page: 10)
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:alert] = "Friend removed successfully"
    redirect_to friendship_path(current_user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back #{ user.full_name }"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Invalid email/password combination, please try again"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out successfully"
    redirect_to root_path
  end
end

app/controllers/user_weights_controller.rb
class UserWeightsController < ApplicationController
  before_action :set_user_weight, only: [:edit, :update, :destroy, :show]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def create
    @user_weight = current_user.user_weights.create(weight_params)
    if @user_weight.save
      flash[:success] = "Weight #{@user_weight.weight} added for #{@user_weight.created_at}"
      redirect_to user_path(current_user)
    else
      flash[:danger] = "Invalid weight entered, range between 0.1 to 999"
      redirect_to user_path(current_user)
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user_weight.update(weight_params)
      flash[:success] = "Weight #{@user_weight.weight} successfully updated at #{@user_weight.updated_at}"
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    @user_weight.destroy
    flash[:danger] = "Weight deleted"
    redirect_to user_path(current_user)
  end


  private
  def weight_params
    params.require(:user_weight).permit(:weight)
  end

  def set_user_weight
    @user_weight = UserWeight.find(params[:id])
  end

  def require_same_user
    if current_user != @user_weight.user
      flash[:danger] = "You do not have access for this action"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the weight tracker #{@user.full_name}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @userWeights = @user.user_weights.order(:created_at).paginate(page: params[:page], per_page: 10)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Information updated successfully"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end


  def destroy
    @user.user_weights.destroy_all
    @user.friendships.where(user_id: @user).destroy_all
    @user.friendships.where(friend_id: @user).destroy_all
    @user.destroy
    flash[:danger] = "User and all associated data is destroyed"
    session[:user_id] = nil
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:danger] = "You do not have access for this action"
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
    if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			log_in user
			@current_user = user
		end
  end

	def logged_in?
    !current_user.nil?
  end

	def require_user
    if !logged_in?
      flash[:danger] = "Not logged to perform that action"
      redirect_to root_path
    end
  end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friendships/show.html.erb
<% if current_user.friends.any? %>
<div align="center">
  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Entered Date</th>
        <th scope="col">Weight</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tracked_friends.each do |friend| %>
      <tr>
        <th scope="row"><%= friend.id %></th>
        <td><%= friend.full_name %></td>
        <td><%= friend.email %></td>
        <td>
          <%= link_to "Show Friend info", user_path(friend),
              class: "btn btn-info" %> |
          <%= link_to "Remove Friend", friendship_path(friend), method: :delete,
              data: {confirm: "Are you sure?"},class: "btn btn-danger" %>
        </td>
      </tr>
      <% end %>
      <div class="digg_pagination">
        <div class="page_info">
          <%= page_entries_info @tracked_friends %>
        </div>
        <%= will_paginate @tracked_friends %>
      </div>

    </tbody>
  </table>
</div>
<% end %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12 col-sm-offset-3">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>' role="alert">
        <a href="#" class="close" data-dismiss="alert">x</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
	<%= link_to "Home", root_path, class: "navbar-brand" %>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<% if logged_in? %>
					<li class="nav-item">
						<%= link_to "Show My Weights", user_path(current_user), class: "nav-link" %>
					</li>
				<li class="nav-item">
					<%= link_to "All Users", users_path, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "My Friends", friendship_path(current_user), class: "nav-link" %>
				</li>
			<% end %>
				<li class="nav-item">
					<% if !logged_in? %>
						<%= link_to "Sign Up", new_user_path, class: "nav-link", tabindex:"-1" %>
					<% end %>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if logged_in? %>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<%= current_user.full_name %>
					</a>
					<div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdown">
						<%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
						<%= link_to "Show profile", user_path(current_user), class: "dropdown-item" %>
						<div class="dropdown-divider"></div>
						<%= link_to "Log Out", logout_path, method: :delete, class: "dropdown-item" %>
					</div>
				<% else %>
						<%= link_to "Log In", login_path, class: "dropdown-item" %>
				</li>
				<% end %>

			</ul>
		</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WeightTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-12">
    <div class="alert alert-danger" role="alert">
      <a href="#" class="close" data-dismiss="alert">x</a>
      <div class="card-heading">
        <h2 class="card-title">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this article from being saved:
        </h2>
        <div class="card-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/user_weights/edit.html.erb
<%= form_for(@user_weight) do |f| %>
  <div class="form-group row">
    <div class="col-form-label col-sm-3">
      <%= f.label :weight %>
    </div>
    <div class="col-sm-4">
      <%= f.number_field :weight, step: 0.1, class: "form-control",
          autofocus: true %>
    </div>
    <%= f.submit "Update", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/user_weights/show.html.erb
<div align="center">
  <% if @user_weight.user.image.attached? %>
    <div>
        <%= image_tag @user_weight.user.image %>
    </div>
  <% end %>
  <h1><%= @user_weight.user.first_name %> <%= @user_weight.user.last_name %></h1>
  <h2><%= @user_weight.weight %></h2>
  <h3><%= @user_weight.created_at %></h3>
  <h3><%= @user_weight.updated_at %></h3>

  <%= link_to 'Update', edit_user_weight_path(@user_weight), class: "btn btn-secondary" %>
</div>

app/views/users/_user_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="col-sm-12 offset-2">
  <%= form_for @user do |f| %>
    <div class="form-group row">
      <div class="col-form-label col-sm-3">
        <%= f.label :first_name %>
      </div>
      <div class="col-sm-4">
        <%= f.text_field :first_name, class: "form-control",
            placeholder: "Enter Your First Name", autofocus: true %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-form-label col-sm-3">
        <%= f.label :last_name %>
      </div>
      <div class="col-sm-4">
        <%= f.text_field :last_name, class: "form-control",
            placeholder: "Enter Your Last Name" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-form-label col-sm-3">
        <%= f.label :email %>
      </div>
      <div class="col-sm-4">
        <%= f.email_field :email, class: "form-control",
            placeholder: "Enter Your Email Address" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-form-label col-sm-3">
        <%= f.label :password %>
      </div>
      <div class="col-sm-4">
        <%= f.password_field :password, class: "form-control",
            placeholder: "Enter Your Password" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-form-label col-sm-3">
        <%= f.label :password_confirmation %>
      </div>
      <div class="col-sm-4">
        <%= f.password_field :password_confirmation, class: "form-control",
            placeholder: "Enter Your Password Confirmation" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-form-label col-sm-3">
        <%= f.label :profile_picture %>
      </div>
      <div class="col-sm-4">
        <%= f.file_field :image, multiple: false %>
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-sm-3 col-sm-10">
        <%= f.submit class: "btn btn-primary"%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h3 align="center">Update your account settings </h3>
<%= render 'user_form' %>

app/views/users/index.html.erb
<table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to "Add to friends", friendships_path(friend: user),
                class:"btn btn-sm btn-warning", method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h3 align="center">Sign Up!</h3>
<%= render 'user_form'%>

app/views/users/show.html.erb
<div align="center">
  <% if @user.image.attached? %>
    <div>
        <%= image_tag @user.image %>
    </div>
  <% end %>
  <h1><%= @user.full_name %></h1>
  <% if current_user == @user %>
    <%= form_for(:user_weight, url: user_weights_path) do |f| %>
      <div class="form-group row">
        <div class="col-form-label col-sm-3">
          <%= f.label :weight %>
        </div>
        <div class="col-sm-4">
          <%= f.number_field :weight, step: 0.1, class: "form-control",
              autofocus: true %>
        </div>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
  <% if @user.user_weights.any? %>
  <%= line_chart @userWeights.pluck(:created_at, :weight),
      xtitle: "Entered Time", ytitle: "Weight"%>
    <table class="table table-striped table-dark">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Entered Date</th>
          <th scope="col">Weight</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @userWeights.each do |user_weight| %>
        <tr>
          <th scope="row"><%= user_weight.id %></th>
          <td><%= user_weight.created_at.to_date.to_formatted_s(:long_ordinal) %></td>
          <td><%= user_weight.weight %></td>
          <td>
            <%= link_to "Edit Weight", edit_user_weight_path(user_weight),
                class: "btn btn-info" %> |
            <%= link_to "Delete Weight", user_weight_path(user_weight),
                method: :delete, data: {confirm: "Are you sure?" },
                class: "btn btn-danger" %>
          </td>
        </tr>
        <% end %>
        <div class="digg_pagination">
          <div class="page_info">
            <%= page_entries_info @userWeights %>
          </div>
          <%= will_paginate @userWeights %>
        </div>

      </tbody>
    </table>
  <% end %>

 <%= link_to "Edit User", edit_user_path(@user), class:"btn btn-primary" %> |
 <%= link_to "Delete User", user_path(@user), method: :delete, class:"btn btn-danger", data: {confirm: "Are you sure?"} %>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron bg-light jumbotron-fluid">
  <div class="container">
    <h1 align="center" class="display-4" >Welcome to Weight Tracker</h1>
    <p  align="center" class="lead">This application is designed to help you keep track of your weight</p>
    <% if !logged_in? %>
      <div align="center">
        <%= link_to "Sign Up", new_user_path, class:"btn btn-secondary" %> |
        <%= link_to 'Log In', login_path, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>